#  docker-compose -f docker-compose.yml config check validate config
version: "3.7"
services:
  vfoxapi:
    image: "richarvey/nginx-php-fpm:latest"
    container_name: vfoxapi
    working_dir: /var/www/html
    restart: "always"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-available/default.conf
      - ./api/:/var/www/html/
    labels:
      com.docker.compose.project: "vfoxapi"
    ports:
      - "8101:80"
    expose:
      - "8101"
    # environment:
      # VIRTUAL_HOST: "vfoxapi.shopsthai.com"
      # ENABLE_IPV6: "true"
      # HOSTNAME: "vfoxapi.shopsthai.com"
      # LANG: C.UTF-8
    # external_links:
    #   - "mariadb"
    network_mode: "bridge"

  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    expose:
      - "9000"    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`dev.portainer`)"
      - "traefik.http.routers.portainer.entrypoints=web"

volumes:
  portainer_data:
  mariadb_data: